import { Card } from './Card';

/** Historical catalog: 100+ verified card records from the surviving PeroPero lists. */
const stages = (name: string) => [1, 20, 40, 60, 80, 100].map((level) => ({
  level,
  image: `https://peropero.fandom.com/wiki/Special:Redirect/file/${encodeURIComponent(name)}.png`,
}));

export const cardDatabase: Card[] = [
  new Card({ id: 'natasha-lutz', name: 'Natasha Lutz', rarity: 'N', type: 'Sexy', maxBaseSed: 2750, imageStages: stages('Natasha Lutz') }),
  new Card({ id: 'akie-ibara', name: 'Akie Ibara', rarity: 'SR', type: 'Babe', maxBaseSed: 11740, imageStages: stages('Akie Ibara') }),
  new Card({ id: 'risa-shimozono', name: 'Risa Shimozono', rarity: 'N', type: 'Sexy', maxBaseSed: 2860, imageStages: stages('Risa Shimozono') }),
  new Card({ id: 'sr-moe-alicia', name: 'Alicia', rarity: 'SR', type: 'Moe', maxBaseSed: 12800, imageStages: stages('Alicia') }),
  new Card({ id: 'sr-moe-ami-osaki', name: 'Ami Osaki', rarity: 'SR', type: 'Moe', maxBaseSed: 11120, imageStages: stages('Ami Osaki') }),
  new Card({ id: 'sr-moe-ann-bamboo', name: 'Ann Bamboo', rarity: 'SR', type: 'Moe', maxBaseSed: 10800, imageStages: stages('Ann Bamboo') }),
  new Card({ id: 'sr-moe-anzu-kitamura', name: 'Anzu Kitamura', rarity: 'SR', type: 'Moe', maxBaseSed: 10470, imageStages: stages('Anzu Kitamura') }),
  new Card({ id: 'sr-moe-aone-kanno', name: 'Aone Kanno', rarity: 'SR', type: 'Moe', maxBaseSed: 10740, imageStages: stages('Aone Kanno') }),
  new Card({ id: 'sr-moe-asumi-konno', name: 'Asumi Konno', rarity: 'SR', type: 'Moe', maxBaseSed: 11040, imageStages: stages('Asumi Konno') }),
  new Card({ id: 'sr-moe-ayano-suruga', name: 'Ayano Suruga', rarity: 'SR', type: 'Moe', maxBaseSed: 11130, imageStages: stages('Ayano Suruga') }),
  new Card({ id: 'sr-moe-ayano-takei', name: 'Ayano Takei', rarity: 'SR', type: 'Moe', maxBaseSed: 10700, imageStages: stages('Ayano Takei') }),
  new Card({ id: 'sr-moe-chino-baren', name: 'Chino Baren', rarity: 'SR', type: 'Moe', maxBaseSed: 10770, imageStages: stages('Chino Baren') }),
  new Card({ id: 'sr-moe-chise-hosokawa', name: 'Chise Hosokawa', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Chise Hosokawa') }),
  new Card({ id: 'sr-moe-daimyoji-hana', name: 'Daimyoji Hana', rarity: 'SR', type: 'Moe', maxBaseSed: 13650, imageStages: stages('Daimyoji Hana') }),
  new Card({ id: 'sr-moe-eri-aoyama', name: 'Eri Aoyama', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Eri Aoyama') }),
  new Card({ id: 'sr-moe-hanbei-takenaka', name: 'Hanbei Takenaka', rarity: 'SR', type: 'Moe', maxBaseSed: 10900, imageStages: stages('Hanbei Takenaka') }),
  new Card({ id: 'sr-moe-hinano-honda', name: 'Hinano Honda', rarity: 'SR', type: 'Moe', maxBaseSed: 10630, imageStages: stages('Hinano Honda') }),
  new Card({ id: 'sr-moe-hiyori-katagiri', name: 'Hiyori Katagiri', rarity: 'SR', type: 'Moe', maxBaseSed: 11000, imageStages: stages('Hiyori Katagiri') }),
  new Card({ id: 'sr-moe-hyuga', name: 'Hyuga', rarity: 'SR', type: 'Moe', maxBaseSed: 11160, imageStages: stages('Hyuga') }),
  new Card({ id: 'sr-moe-ichika-egawa', name: 'Ichika Egawa', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Ichika Egawa') }),
  new Card({ id: 'sr-moe-ichiko-yamabuki', name: 'Ichiko Yamabuki', rarity: 'SR', type: 'Moe', maxBaseSed: 10880, imageStages: stages('Ichiko Yamabuki') }),
  new Card({ id: 'sr-moe-imamoriko-peach', name: 'Imamoriko Peach', rarity: 'SR', type: 'Moe', maxBaseSed: 11180, imageStages: stages('Imamoriko Peach') }),
  new Card({ id: 'sr-moe-iriya-and-yoel-ur', name: 'Iriya & Yoel Ur', rarity: 'SR', type: 'Moe', maxBaseSed: 10930, imageStages: stages('Iriya & Yoel Ur') }),
  new Card({ id: 'sr-moe-kaede-misu', name: 'Kaede Misu', rarity: 'SR', type: 'Moe', maxBaseSed: 10520, imageStages: stages('Kaede Misu') }),
  new Card({ id: 'sr-moe-kanade-hazama', name: 'Kanade Hazama', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Kanade Hazama') }),
  new Card({ id: 'sr-moe-kanae', name: 'Kanae', rarity: 'SR', type: 'Moe', maxBaseSed: 11100, imageStages: stages('Kanae') }),
  new Card({ id: 'sr-moe-kasumi', name: 'Kasumi', rarity: 'SR', type: 'Moe', maxBaseSed: 10920, imageStages: stages('Kasumi') }),
  new Card({ id: 'sr-moe-kie-sawakawa', name: 'Kie Sawakawa', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Kie Sawakawa') }),
  new Card({ id: 'sr-moe-kikyo-nekomura', name: 'Kikyo Nekomura', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Kikyo Nekomura') }),
  new Card({ id: 'sr-moe-koharu-yuishiro', name: 'Koharu Yuishiro', rarity: 'SR', type: 'Moe', maxBaseSed: 10580, imageStages: stages('Koharu Yuishiro') }),
  new Card({ id: 'sr-moe-konoha-suzumura', name: 'Konoha Suzumura', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Konoha Suzumura') }),
  new Card({ id: 'sr-moe-koromo-yugure', name: 'Koromo Yugure', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Koromo Yugure') }),
  new Card({ id: 'sr-moe-kotori-hinakawa', name: 'Kotori Hinakawa', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Kotori Hinakawa') }),
  new Card({ id: 'sr-moe-kurashiki-eri', name: 'Kurashiki Eri', rarity: 'SR', type: 'Moe', maxBaseSed: 10920, imageStages: stages('Kurashiki Eri') }),
  new Card({ id: 'sr-moe-maika-ibuki', name: 'Maika Ibuki', rarity: 'SR', type: 'Moe', maxBaseSed: 10730, imageStages: stages('Maika Ibuki') }),
  new Card({ id: 'sr-moe-makie-sakata', name: 'Makie Sakata', rarity: 'SR', type: 'Moe', maxBaseSed: 10900, imageStages: stages('Makie Sakata') }),
  new Card({ id: 'sr-moe-makiko-shinano', name: 'Makiko Shinano', rarity: 'SR', type: 'Moe', maxBaseSed: 10680, imageStages: stages('Makiko Shinano') }),
  new Card({ id: 'sr-moe-mako-itsukida', name: 'Mako Itsukida', rarity: 'SR', type: 'Moe', maxBaseSed: 10550, imageStages: stages('Mako Itsukida') }),
  new Card({ id: 'sr-moe-mau-oizumi', name: 'Mau Oizumi', rarity: 'SR', type: 'Moe', maxBaseSed: 11020, imageStages: stages('Mau Oizumi') }),
  new Card({ id: 'sr-moe-mayuko-abe', name: 'Mayuko Abe', rarity: 'SR', type: 'Moe', maxBaseSed: 10200, imageStages: stages('Mayuko Abe') }),
  new Card({ id: 'sr-moe-mei-nishiura', name: 'Mei Nishiura', rarity: 'SR', type: 'Moe', maxBaseSed: 10910, imageStages: stages('Mei Nishiura') }),
  new Card({ id: 'sr-moe-megu-kogami', name: 'Megu Kogami', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Megu Kogami') }),
  new Card({ id: 'sr-moe-mika-shiina', name: 'Mika Shiina', rarity: 'SR', type: 'Moe', maxBaseSed: 10800, imageStages: stages('Mika Shiina') }),
  new Card({ id: 'sr-moe-minami-okishima', name: 'Minami Okishima', rarity: 'SR', type: 'Moe', maxBaseSed: 10550, imageStages: stages('Minami Okishima') }),
  new Card({ id: 'sr-moe-minami-yazawa', name: 'Minami Yazawa', rarity: 'SR', type: 'Moe', maxBaseSed: 11120, imageStages: stages('Minami Yazawa') }),
  new Card({ id: 'sr-moe-mio-yuuki', name: 'Mio Yuuki', rarity: 'SR', type: 'Moe', maxBaseSed: 10650, imageStages: stages('Mio Yuuki') }),
  new Card({ id: 'sr-moe-misaki-tachibana', name: 'Misaki Tachibana', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Misaki Tachibana') }),
  new Card({ id: 'sr-moe-mitsuki-amane', name: 'Mitsuki Amane', rarity: 'SR', type: 'Moe', maxBaseSed: 11120, imageStages: stages('Mitsuki Amane') }),
  new Card({ id: 'sr-moe-miu', name: 'Miu', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Miu') }),
  new Card({ id: 'sr-moe-miwa-kisaragi', name: 'Miwa Kisaragi', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Miwa Kisaragi') }),
  new Card({ id: 'sr-moe-miyuki-morizuka', name: 'Miyuki Morizuka', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Miyuki Morizuka') }),
  new Card({ id: 'sr-moe-moena-kawahara', name: 'Moena Kawahara', rarity: 'SR', type: 'Moe', maxBaseSed: 10960, imageStages: stages('Moena Kawahara') }),
  new Card({ id: 'sr-moe-momoko-shirai', name: 'Momoko Shirai', rarity: 'SR', type: 'Moe', maxBaseSed: 10690, imageStages: stages('Momoko Shirai') }),
  new Card({ id: 'sr-moe-motoko-ebihara', name: 'Motoko Ebihara', rarity: 'SR', type: 'Moe', maxBaseSed: 11030, imageStages: stages('Motoko Ebihara') }),
  new Card({ id: 'sr-moe-mutsuki-arase', name: 'Mutsuki Arase', rarity: 'SR', type: 'Moe', maxBaseSed: 10770, imageStages: stages('Mutsuki Arase') }),
  new Card({ id: 'sr-moe-nami-wakabayashi', name: 'Nami Wakabayashi', rarity: 'SR', type: 'Moe', maxBaseSed: 10650, imageStages: stages('Nami Wakabayashi') }),
  new Card({ id: 'sr-moe-nanaki-amatsu', name: 'Nanaki Amatsu', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Nanaki Amatsu') }),
  new Card({ id: 'sr-moe-naoko-noguchi', name: 'Naoko Noguchi', rarity: 'SR', type: 'Moe', maxBaseSed: 10700, imageStages: stages('Naoko Noguchi') }),
  new Card({ id: 'sr-moe-naomi-hashimoto', name: 'Naomi Hashimoto', rarity: 'SR', type: 'Moe', maxBaseSed: 10990, imageStages: stages('Naomi Hashimoto') }),
  new Card({ id: 'sr-moe-nina-manami', name: 'Nina Manami', rarity: 'SR', type: 'Moe', maxBaseSed: 11020, imageStages: stages('Nina Manami') }),
  new Card({ id: 'sr-moe-nishizawa-mandarin', name: 'Nishizawa Mandarin', rarity: 'SR', type: 'Moe', maxBaseSed: 10880, imageStages: stages('Nishizawa Mandarin') }),
  new Card({ id: 'sr-moe-nozomi', name: 'Nozomi', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Nozomi') }),
  new Card({ id: 'sr-moe-raika-seno', name: 'Raika Seno', rarity: 'SR', type: 'Moe', maxBaseSed: 10760, imageStages: stages('Raika Seno') }),
  new Card({ id: 'sr-moe-rakka-koizumi', name: 'Rakka Koizumi', rarity: 'SR', type: 'Moe', maxBaseSed: 11040, imageStages: stages('Rakka Koizumi') }),
  new Card({ id: 'sr-moe-reina-tanba', name: 'Reina Tanba', rarity: 'SR', type: 'Moe', maxBaseSed: 10640, imageStages: stages('Reina Tanba') }),
  new Card({ id: 'sr-moe-rena-kazami', name: 'Rena Kazami', rarity: 'SR', type: 'Moe', maxBaseSed: 10710, imageStages: stages('Rena Kazami') }),
  new Card({ id: 'sr-moe-renka-itabashi', name: 'Renka Itabashi', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Renka Itabashi') }),
  new Card({ id: 'sr-moe-rie-obata', name: 'Rie Obata', rarity: 'SR', type: 'Moe', maxBaseSed: 10620, imageStages: stages('Rie Obata') }),
  new Card({ id: 'sr-moe-rika-kojo', name: 'Rika Kojo', rarity: 'SR', type: 'Moe', maxBaseSed: 10770, imageStages: stages('Rika Kojo') }),
  new Card({ id: 'sr-moe-riku-haneoka', name: 'Riku Haneoka', rarity: 'SR', type: 'Moe', maxBaseSed: 10850, imageStages: stages('Riku Haneoka') }),
  new Card({ id: 'sr-moe-rina-kaneshiro', name: 'Rina Kaneshiro', rarity: 'SR', type: 'Moe', maxBaseSed: 10390, imageStages: stages('Rina Kaneshiro') }),
  new Card({ id: 'sr-moe-rinne-sawano', name: 'Rinne Sawano', rarity: 'SR', type: 'Moe', maxBaseSed: 10750, imageStages: stages('Rinne Sawano') }),
  new Card({ id: 'sr-moe-runa-kamiwano', name: 'Runa Kamiwano', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Runa Kamiwano') }),
  new Card({ id: 'sr-moe-ruri-kuroba', name: 'Ruri Kuroba', rarity: 'SR', type: 'Moe', maxBaseSed: 10860, imageStages: stages('Ruri Kuroba') }),
  new Card({ id: 'sr-moe-ryo-kurusu', name: 'Ryo Kurusu', rarity: 'SR', type: 'Moe', maxBaseSed: 10680, imageStages: stages('Ryo Kurusu') }),
  new Card({ id: 'sr-moe-satoko-koshigaya', name: 'Satoko Koshigaya', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Satoko Koshigaya') }),
  new Card({ id: 'sr-moe-sayo-matsudera', name: 'Sayo Matsudera', rarity: 'SR', type: 'Moe', maxBaseSed: 10710, imageStages: stages('Sayo Matsudera') }),
  new Card({ id: 'sr-moe-shigen-houtou', name: 'Shigen Houtou', rarity: 'SR', type: 'Moe', maxBaseSed: 10770, imageStages: stages('Shigen Houtou') }),
  new Card({ id: 'sr-moe-shiranui-yuzuriha', name: 'Shiranui Yuzuriha', rarity: 'SR', type: 'Moe', maxBaseSed: 11090, imageStages: stages('Shiranui Yuzuriha') }),
  new Card({ id: 'sr-moe-shizuku', name: 'Shizuku', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Shizuku') }),
  new Card({ id: 'sr-moe-shizuka-peach', name: 'Shizuka Peach', rarity: 'SR', type: 'Moe', maxBaseSed: 12880, imageStages: stages('Shizuka Peach') }),
  new Card({ id: 'sr-moe-shizuku-momose', name: 'Shizuku Momose', rarity: 'SR', type: 'Moe', maxBaseSed: 11030, imageStages: stages('Shizuku Momose') }),
  new Card({ id: 'sr-moe-sora-shimada', name: 'Sora Shimada', rarity: 'SR', type: 'Moe', maxBaseSed: 10890, imageStages: stages('Sora Shimada') }),
  new Card({ id: 'sr-moe-souko-yukawa', name: 'Souko Yukawa', rarity: 'SR', type: 'Moe', maxBaseSed: 10560, imageStages: stages('Souko Yukawa') }),
  new Card({ id: 'sr-moe-suzuka-yamashiro', name: 'Suzuka Yamashiro', rarity: 'SR', type: 'Moe', maxBaseSed: 10950, imageStages: stages('Suzuka Yamashiro') }),
  new Card({ id: 'sr-moe-toki-shirodera', name: 'Toki Shirodera', rarity: 'SR', type: 'Moe', maxBaseSed: 10670, imageStages: stages('Toki Shirodera') }),
  new Card({ id: 'sr-moe-tomoe-inukai', name: 'Tomoe Inukai', rarity: 'SR', type: 'Moe', maxBaseSed: 11000, imageStages: stages('Tomoe Inukai') }),
  new Card({ id: 'sr-moe-touka-hazenoki', name: 'Touka Hazenoki', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Touka Hazenoki') }),
  new Card({ id: 'sr-moe-tsukiho-agatsuma', name: 'Tsukiho Agatsuma', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Tsukiho Agatsuma') }),
  new Card({ id: 'sr-moe-ui-takayama', name: 'Ui Takayama', rarity: 'SR', type: 'Moe', maxBaseSed: 11010, imageStages: stages('Ui Takayama') }),
  new Card({ id: 'sr-moe-ureha-takagi', name: 'Ureha Takagi', rarity: 'SR', type: 'Moe', maxBaseSed: 11030, imageStages: stages('Ureha Takagi') }),
  new Card({ id: 'sr-moe-uzuki-kiki', name: 'Uzuki Kiki', rarity: 'SR', type: 'Moe', maxBaseSed: 10780, imageStages: stages('Uzuki Kiki') }),
  new Card({ id: 'sr-moe-vorvados', name: 'Vorvados', rarity: 'SR', type: 'Moe', maxBaseSed: 11170, imageStages: stages('Vorvados') }),
  new Card({ id: 'sr-moe-yakumo-hanekawa', name: 'Yakumo Hanekawa', rarity: 'SR', type: 'Moe', maxBaseSed: 10790, imageStages: stages('Yakumo Hanekawa') }),
  new Card({ id: 'sr-moe-yokozawa-minoru', name: 'Yokozawa Minoru', rarity: 'SR', type: 'Moe', maxBaseSed: 10800, imageStages: stages('Yokozawa Minoru') }),
  new Card({ id: 'sr-moe-yui-masuda', name: 'Yui Masuda', rarity: 'SR', type: 'Moe', maxBaseSed: 10680, imageStages: stages('Yui Masuda') }),
  new Card({ id: 'sr-moe-yukine-hiragi', name: 'Yukine Hiragi', rarity: 'SR', type: 'Moe', maxBaseSed: 10830, imageStages: stages('Yukine Hiragi') }),
  new Card({ id: 'sr-moe-yumiko-harui', name: 'Yumiko Harui', rarity: 'SR', type: 'Moe', maxBaseSed: 10660, imageStages: stages('Yumiko Harui') }),
  new Card({ id: 'sr-moe-yurina-kitazawa', name: 'Yurina Kitazawa', rarity: 'SR', type: 'Moe', maxBaseSed: 10630, imageStages: stages('Yurina Kitazawa') }),
  new Card({ id: 'sr-moe-yuzu-kudo', name: 'Yuzu Kudo', rarity: 'SR', type: 'Moe', maxBaseSed: 10490, imageStages: stages('Yuzu Kudo') }),
  new Card({ id: 'sr-moe-aika-aoki', name: 'Aika Aoki', rarity: 'SR', type: 'Moe', maxBaseSed: 11730, imageStages: stages('Aika Aoki') }),
  new Card({ id: 'sr-moe-airi-togawa', name: 'Airi Togawa', rarity: 'SR', type: 'Moe', maxBaseSed: 11720, imageStages: stages('Airi Togawa') }),
  new Card({ id: 'sr-moe-akemi-sakai', name: 'Akemi Sakai', rarity: 'SR', type: 'Moe', maxBaseSed: 11870, imageStages: stages('Akemi Sakai') }),
];
